### ISSUE TITLE
Addon not available on mobile

### ISSUE THREAD

**Issue by Huy-Ngo** [dpacassi/view-page-source-mobile#1]
![Screenshot_2021-04-11-17-28-03-800_org mozilla firefox](https://user-images.githubusercontent.com/19296926/114300609-550f7300-9aeb-11eb-9900-ebd40fe14e56.jpg)

When I go to the addon page, the button is grayed, indicating the addon is not available for mobile.

**Comment by nicolasform** [comment]
Same for me (Aug 25th 2021)

**Comment by dpacassi** [comment]
Hi @Huy-Ngo and @nicolasform 

First off, sorry for the late reply.
Secondly, unfortunately, Firefox for Android allows now only the installation of a limited, recommended list of web extensions.

When I first developed this web extension, people could install on Firefox for Android any web extension just like on Desktop. However this changed a few months back and Mozilla is still working on allowing more web extensions to be installed.

Unfortunately there's nothing I can do from my side, sorry.
You can read more about this on the Mozilla support blog:
https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android

**Comment by nicolasform** [comment]
That's a bad news! Do you know if there is an issue in Bugzilla (https://bugzilla.mozilla.org/) about that? I didn't find one, maybe we could create one.

**Comment by dpacassi** [comment]
I don't think there's an issue on Bugzilla about this as it's not seen as a bug but as a feature.
I quote from https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android:

> Will more extensions be supported in the future?
> We would like to enable support for more extensions on the new Firefox for Android experience and we are currently evaluating ways we can do so without introducing the compatibility and security issues from the previous version of our mobile browser for Android. We'll provide updates as soon as we have more details. 

It's considered to be a safety feature, though I personally don't get how they allow Desktop Firefox to install published web extensions, shouldn't it be unsafe on Desktop too?

Anyway, let me know if you create an issue and I'll happily contribute my support :)
